### ISSUE TITLE
resolve yeoman build errors

### ISSUE THREAD

**Issue by giladgray** [whichbus/whichbus-bbb#18]
there's sure to be a lot of them. cannot distribute code until build errors are resolved.

**Comment by dalanmiller** [comment]
Copy output of errors here?

**Comment by giladgray** [comment]
there's only one error at a time--as far as it gets before dying. mainly concerned with template compilation, I'm investigating using Handlebars in hope of a better experience: https://github.com/yeoman/yeoman/wiki/Handlebars-integration

**Comment by giladgray** [comment]
Handlebars was quite straightforward actually. I'm an even bigger fan now. :+1: 

All that's left (I hope) is getting images to work :camera:. Could remove the rev block from Gruntfile? :palm_tree: :sun_with_face: :tada:

**Comment by dalanmiller** [comment]
Links to the issues for revv'd images and possible but kludgey solutions.

Basically `rev` in Gruntfile.js needs to have this:

```
rev: {
   img: ['images/**','!images/ignore/**']
}
```

https://github.com/yeoman/yeoman/issues/822

http://stackoverflow.com/a/14227500

https://github.com/yeoman/yeoman/issues/406#issuecomment-9826527
